redis.lo: /var/www/html/github/php-redis/phpredis-master/redis.c
	$(LIBTOOL) --mode=compile $(CC)  -I. -I/var/www/html/github/php-redis/phpredis-master $(COMMON_FLAGS) $(CFLAGS_CLEAN) $(EXTRA_CFLAGS)  -c /var/www/html/github/php-redis/phpredis-master/redis.c -o redis.lo 
library.lo: /var/www/html/github/php-redis/phpredis-master/library.c
	$(LIBTOOL) --mode=compile $(CC)  -I. -I/var/www/html/github/php-redis/phpredis-master $(COMMON_FLAGS) $(CFLAGS_CLEAN) $(EXTRA_CFLAGS)  -c /var/www/html/github/php-redis/phpredis-master/library.c -o library.lo 
redis_session.lo: /var/www/html/github/php-redis/phpredis-master/redis_session.c
	$(LIBTOOL) --mode=compile $(CC)  -I. -I/var/www/html/github/php-redis/phpredis-master $(COMMON_FLAGS) $(CFLAGS_CLEAN) $(EXTRA_CFLAGS)  -c /var/www/html/github/php-redis/phpredis-master/redis_session.c -o redis_session.lo 
redis_array.lo: /var/www/html/github/php-redis/phpredis-master/redis_array.c
	$(LIBTOOL) --mode=compile $(CC)  -I. -I/var/www/html/github/php-redis/phpredis-master $(COMMON_FLAGS) $(CFLAGS_CLEAN) $(EXTRA_CFLAGS)  -c /var/www/html/github/php-redis/phpredis-master/redis_array.c -o redis_array.lo 
redis_array_impl.lo: /var/www/html/github/php-redis/phpredis-master/redis_array_impl.c
	$(LIBTOOL) --mode=compile $(CC)  -I. -I/var/www/html/github/php-redis/phpredis-master $(COMMON_FLAGS) $(CFLAGS_CLEAN) $(EXTRA_CFLAGS)  -c /var/www/html/github/php-redis/phpredis-master/redis_array_impl.c -o redis_array_impl.lo 
$(phplibdir)/redis.la: ./redis.la
	$(LIBTOOL) --mode=install cp ./redis.la $(phplibdir)

./redis.la: $(shared_objects_redis) $(REDIS_SHARED_DEPENDENCIES)
	$(LIBTOOL) --mode=link $(CC) $(COMMON_FLAGS) $(CFLAGS_CLEAN) $(EXTRA_CFLAGS) $(LDFLAGS) -o $@ -export-dynamic -avoid-version -prefer-pic -module -rpath $(phplibdir) $(EXTRA_LDFLAGS) $(shared_objects_redis) $(REDIS_SHARED_LIBADD)

